#!/usr/bin/env python
import os,sys
from subprocess import Popen, PIPE

args = sys.argv[1:]

for alias in args :
	alias_file = open("/etc/avahi/aliases")
	alias_found = False

	for line in alias_file :
		line = line.rstrip("\n")
		print("looking for [%s] to match [%s]", (alias, line) )
		if alias == line :
			print("%s : already exists : " % alias)
			alias_found = True

	alias_file.close()

	if not alias_found :
		print("%s : added" % alias)
		alias_file = open("/etc/avahi/aliases","a")
		alias_file.write("%s\n" % alias)
		alias_file.close()

os.system("avahi-publish-aliases")

