#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          avahi-aliases
# Required-Start:    $remote_fs $syslog avahi
# Required-Stop:     $remote_fs $syslog avahi
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start avahi aliases at boot time
# Description:       Enable avahi aliases from /etc/avahi/aliases 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=avahi-aliases
DAEMON=/usr/bin/avahi-publish-aliases
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  start)
	$DAEMON
	;;
	
  reload)
	$DAEMON
	;;
	
  stop)
	kill $(cat /tmp/avahi-publish-alias.pid) && rm /tmp/avahi-publish-alias.pid
	;;

  *)
        echo "Usage: $SCRIPTNAME {start|stop|reload}" >&2
        exit 3
        ;;
esac
