#!/usr/bin/env python

import os, sys
from subprocess import Popen
import glob

alias_file_path = "/etc/avahi/aliases"
alias_dir_glob = "/etc/avahi/aliases.d/*"
alias_file = open(alias_file_path)
alias_dir = glob.glob(alias_dir_glob)
aliases = set()

for file in alias_dir :
	contents = open(file, 'r')
	for line in contents :
		entry = line.strip('\n')
		if len(entry) > 0 :
			aliases.add(entry)

for line in alias_file :
	entry = line.strip('\n')
	if len(entry) > 0 :
		aliases.add(entry)

for alias in aliases:
	print alias 
